#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NTAssign;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-compatible\"");

WriteLiteral(" content=\"IE=edge, chrome=1\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 324), Tuple.Create("\"", 344)
, Tuple.Create(Tuple.Create("", 331), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 331), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"http://www.chem.pku.edu.cn/liy/labhomepage\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 693), Tuple.Create("\"", 727)
, Tuple.Create(Tuple.Create("", 699), Tuple.Create<System.Object, System.Int32>(Href("~/Content/banner_waifu2x.png")
, 699), false)
);

WriteLiteral(" style=\"width: 75%;\"");

WriteLiteral(" class=\"center-block\"");

WriteLiteral(" /></a>\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>&copy; 2009&ndash;");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
                            Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" Nanomaterials & Nanostructures Group, Peking University. All rights reserved.</p" +
">\r\n            <p");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral(">\r\n                Total visitors:\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    var sc_project = 11459189;
                    var sc_invisible = 0;
                    var sc_security = ""2c749830"";
                    var sc_text = 2;
                    var scJsHost = ((""https:"" == document.location.protocol) ?
                        ""https://secure."" : ""http://www."");
                    document.write(""<sc"" + ""ript type='text/javascript' src='"" +
                        scJsHost +
                        ""statcounter.com/counter/counter.js'></"" + ""script>"");
                </script>
                <noscript>
                    <div");

WriteLiteral(" class=\"statcounter\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" title=\"Web Analytics\"");

WriteLiteral("\r\n                           href=\"http://statcounter.com/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" class=\"statcounter\"");

WriteLiteral("\r\n                                 src=\"//c.statcounter.com/11459189/0/2c749830/0" +
"/\"");

WriteLiteral("\r\n                                 alt=\"Web Analytics\"");

WriteLiteral(@">
                        </a>
                    </div>
                </noscript>
            </p>
            <p>
                Please contact <b>Prof. Juan Yang, yang_juan(at)pku.edu.cn</b> for any scientific issues.<br />
                Please contact <b>Sida Sun, accel(at)pku.edu.cn</b> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2340), Tuple.Create("\"", 2359)
, Tuple.Create(Tuple.Create("", 2347), Tuple.Create<System.Object, System.Int32>(Href("~/humans.txt")
, 2347), false)
);

WriteLiteral(">(site developer)</a>  for any technical assistance.\r\n            </p>\r\n        <" +
"/footer>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-" +
"AMS_SVG-full,Safe&locale=en\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/x-mathjax-config\"");

WriteLiteral(@">
        MathJax.Hub.Config({
        showProcessingMessages: false,
        showMathMenu: false,
        messageStyle: ""none"",
        tex2jax: {
        processEscapes: true,
        preview: ""none""
        }
        });
        MathJax.Hub.Register.StartupHook(""End"", function () {
        $("".math"").removeClass(""math"");
        });
        MathJax.Hub.Register.MessageHook(""New Math"", function () {
        $("".math"").removeClass(""math"");
        });
    </script>
");

WriteLiteral("    ");

            
            #line 72 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 73 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/flot"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3260), Tuple.Create("\"", 3283)
, Tuple.Create(Tuple.Create("", 3266), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/main.js")
, 3266), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
