#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NTAssign;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Step3.cshtml")]
    public partial class _Views_Home_Step3_cshtml_ : System.Web.Mvc.WebViewPage<NTAssign.Models.PlotModel>
    {
        public _Views_Home_Step3_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\Step3.cshtml"
  
    ViewBag.Title = "Step3";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <style>\r\n        ");

WriteLiteral("@media (max-width: 768px) {\r\n            html, body {\r\n                min-width:" +
" 768px;\r\n            }\r\n        }\r\n    </style>\r\n");

});

WriteLiteral("<h1");

WriteLiteral(" class=\"math\"");

WriteLiteral(">\r\n    Step 3 <small>");

            
            #line 17 "..\..\Views\Home\Step3.cshtml"
             Write(Energy.envArr[Model.type]);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n</h1>\r\n<hr />\r\n<h2");

WriteLiteral(" class=\"math\"");

WriteLiteral(">Results</h2>\r\n<div");

WriteLiteral(" id=\"body-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <!-- the plot -->\r\n        <div");

WriteLiteral(" class=\"col-md-6 col-xs-12 math\"");

WriteLiteral(" oncontextmenu=\"return false\"");

WriteLiteral(" onmousedown=\"return false\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-offset-2 col-md-offset-6 axis-label\"");

WriteLiteral(" style=\"text-align: center; font-size: 20px; color: #0000FF\"");

WriteLiteral(">\r\n                    \\(\\omega_{\\mathrm{RBM}}\\ (\\mathrm{cm^{-1}})\\)\r\n           " +
"     </div>\r\n            </div>\r\n            <br />\r\n            <div");

WriteLiteral(" id=\"plot-container\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div>\r\n                    <div");

WriteLiteral(" style=\"position: absolute; top: 70%; left: 2%; font-size: 20px; transform:rotate" +
"(-90deg); transform-origin: top left;\"");

WriteLiteral(" class=\"axis-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 34 "..\..\Views\Home\Step3.cshtml"
                   Write(Html.Raw(Model.YAxisLabel()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" id=\"plot-placeholder\"");

WriteLiteral(" style=\"width: 550px; height: 400px; font-family: serif;\"");

WriteLiteral(" class=\"col-md-offset-1 col-xs-offset-1\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-offset-2 col-md-offset-5 axis-label\"");

WriteLiteral(" style=\"text-align: center; font-size: 20px; color: #FF0000\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Home\Step3.cshtml"
               Write(Html.Raw(Model.XAxisLabel()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <!-- end of" +
" plot -->\r\n\r\n        <div");

WriteLiteral(" class=\"col-lg-5 col-md-4 col-xs-8 col-lg-offset-0_5 col-md-offset-1_5 col-xs-off" +
"set-1 math changing_height\"");

WriteLiteral(">\r\n            <br />\r\n            <br />\r\n            <p");

WriteLiteral(" id=\"resultDiv\"");

WriteAttribute("class", Tuple.Create(" class=\"", 1877), Tuple.Create("\"", 2001)
            
            #line 50 "..\..\Views\Home\Step3.cshtml"
, Tuple.Create(Tuple.Create("", 1885), Tuple.Create<System.Object, System.Int32>( 
                Model.ar != AssignResult.error ? "alert-success" : "alert-error"
                
            
            #line default
            #line hidden
, 1885), false)
, Tuple.Create(Tuple.Create(" ", 1989), Tuple.Create("text-center", 1990), true)
);

WriteLiteral(" style=\"padding: 12px; border-radius: 4px; font-size: 24px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\Home\Step3.cshtml"
           Write(Html.Raw(Model.resultString));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n            <div");

WriteLiteral(" style=\"font-size: 18px; border-radius: 4px; border: 2px solid #808080;\"");

WriteLiteral(" class=\"bottom-div clearfix\"");

WriteLiteral(">\r\n");

            
            #line 56 "..\..\Views\Home\Step3.cshtml"
                
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Home\Step3.cshtml"
                 if (Model.pointType == "green")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p><font");

WriteLiteral(" style=\"color: rgb(12, 180, 15);\"");

WriteLiteral(">&#11046;</font> \\(E_{ii}\\) vs. \\(\\omega_\\mathrm{RBM}\\)</p>\r\n");

            
            #line 59 "..\..\Views\Home\Step3.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p><font");

WriteLiteral(" style=\"color: rgb(255, 0, 0); font-weight: 900;\"");

WriteLiteral(">&#9632;</font> &nbsp;\\(E_{ii}\\) difference vs. \\(E_{ii}\\) average</p>\r\n");

            
            #line 63 "..\..\Views\Home\Step3.cshtml"
                    if (Model.BluePoint() != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p><font");

WriteLiteral(" style=\"color: rgb(0, 0, 255); font-weight: 900;\"");

WriteLiteral(">&#11046;</font> \\(E_{ii}\\) difference vs. \\(\\omega_\\mathrm{RBM}\\)</p>\r\n");

            
            #line 66 "..\..\Views\Home\Step3.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    <font");

WriteLiteral(" style=\"color: rgb(12, 127, 15); font-weight: 900;\"");

WriteLiteral(">&mdash;</font>\r\n                    \\(532\\ \\mathrm{nm}\\) laser (\\(2.33\\ \\mathrm{" +
"eV}\\))\r\n                </p>\r\n                <p>\r\n                    <font");

WriteLiteral(" style=\"color: rgb(245, 0, 0); font-weight: 900;\"");

WriteLiteral(">&mdash;</font>\r\n                    \\(633\\ \\mathrm{nm}\\) laser (\\(1.96\\ \\mathrm{" +
"eV}\\))\r\n                </p>\r\n                <p>\r\n                    <font");

WriteLiteral(" style=\"color: rgb(136, 136, 136); font-weight: 900;\"");

WriteLiteral(@">&mdash;</font>
                    \(785\ \mathrm{nm}\) laser (\(1.58\ \mathrm{eV}\))
                </p>
                <p>
                    Laser resonance window: \(\pm100\ \mathrm{meV}\)
                </p>
            </div>
        </div>
    </div>
</div>

");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

            
            #line 90 "..\..\Views\Home\Step3.cshtml"
    
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\Home\Step3.cshtml"
      
        if (Model.ar != AssignResult.error)
        {
            var (all, all_label) = Model.All();
            var (result, result_label) = Model.Result();
            var (rbm, rbm_label, rbm_pos) = Model.RBM();

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var params = {\r\n                    point: " +
"");

            
            #line 98 "..\..\Views\Home\Step3.cshtml"
                      Write(Html.Raw(Model.Point()));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    pointType: \"");

            
            #line 99 "..\..\Views\Home\Step3.cshtml"
                           Write(Model.pointType);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    bluePoint: ");

            
            #line 100 "..\..\Views\Home\Step3.cshtml"
                           Write(Model.BluePoint() ?? "null");

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    isMetal: ");

            
            #line 101 "..\..\Views\Home\Step3.cshtml"
                        Write(Html.Raw(Model.IsMetal()));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    all: ");

            
            #line 102 "..\..\Views\Home\Step3.cshtml"
                    Write(Html.Raw(all));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    all_label: ");

            
            #line 103 "..\..\Views\Home\Step3.cshtml"
                          Write(Html.Raw(all_label));

            
            #line default
            #line hidden
WriteLiteral(", //allLabel is rather ugly\r\n                    result: ");

            
            #line 104 "..\..\Views\Home\Step3.cshtml"
                       Write(Html.Raw(result));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    result_label: ");

            
            #line 105 "..\..\Views\Home\Step3.cshtml"
                             Write(Html.Raw(result_label));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    rbm: ");

            
            #line 106 "..\..\Views\Home\Step3.cshtml"
                    Write(Html.Raw(rbm));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    rbm_label: ");

            
            #line 107 "..\..\Views\Home\Step3.cshtml"
                          Write(Html.Raw(rbm_label));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    rbm_pos: ");

            
            #line 108 "..\..\Views\Home\Step3.cshtml"
                        Write(Html.Raw(rbm_pos));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    JSLint: \"f**k JSLint for \'expression expected\' after razor" +
", and I don\'t want to add trailing comma\"\r\n                };\r\n                $" +
"(drawPlot(\"plot-placeholder\", params));\r\n            </script>\r\n");

            
            #line 113 "..\..\Views\Home\Step3.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <script>
                $("".axis-label"").remove();
                var $p = $(""#plot-placeholder"");
                $p.html(""No Image"");
                $p.css({
                    ""border"": ""2px dashed #000000"",
                    ""font-size"": ""50px"",
                    ""line-height"": ""400px"",
                    ""text-align"": ""center"",
                    ""vertical-align"": ""center"",
                    ""font-family"": ""Arial, sans-serif""
                });
            </script>
");

            
            #line 129 "..\..\Views\Home\Step3.cshtml"
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
