#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NTAssign;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Step1.cshtml")]
    public partial class _Views_Home_Step1_cshtml_ : System.Web.Mvc.WebViewPage<NTAssign.Models.AssignModel>
    {
        public _Views_Home_Step1_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\Step1.cshtml"
  
    ViewBag.Title = "CNT Assign";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <style>\r\n    </style>\r\n");

});

WriteLiteral("<h3");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n    (n,m) Assignment Program for SWNTs Under Complex Environments\r\n</h3>\r\n<h1>" +
"Step 1</h1>\r\n\r\n<hr />\r\n");

            
            #line 17 "..\..\Views\Home\Step1.cshtml"
 using (Html.BeginForm("Step2", "Home"))
{
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Home\Step1.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Home\Step1.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal math\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"selectEnv\"");

WriteLiteral(" class=\"control-label col-lg-3 col-md-4 col-sm-5 col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(">Please select the SWNT sample type:</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-3 col-md-3_5 col-sm-4 col-xs-6 col-xs-offset-0_5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Home\Step1.cshtml"
           Write(Html.DropDownListFor(model => model.Env, ViewBag.slEnv as List<SelectListItem>, new { id = "selectEnv", @class = "form-control selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-1 col-md-1_5 col-sm-2 col-xs-2 col-xs-offset-0_5\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-offset-0_5 col-lg-4 col-md-offset-0 col-md-3 col-sm-offset-0_5 mar" +
"gin-xs-top col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(" style=\"height: 100px; overflow-y: scroll;\"");

WriteLiteral(@">
                <h4>Update Log</h4>
                <p>
                    <b>1.0.1_beta &mdash; 2017/9/30</b><br />
                    - Small adjustment. Fixed: diameter minimum when \(p\lt6\) 
                </p>
                <p>
                    <b>1.0.0_beta &mdash; 2017/9/25</b><br />
                    - First release.
                </p>
            </div>
        </div>
    </div>
");

            
            #line 42 "..\..\Views\Home\Step1.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
