#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NTAssign;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Step2.cshtml")]
    public partial class _Views_Home_Step2_cshtml_ : System.Web.Mvc.WebViewPage<NTAssign.Models.AssignModel>
    {
        public _Views_Home_Step2_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\Step2.cshtml"
  
    ViewBag.Title = "Step2";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <style>\r\n        #chart {\r\n            width: 400px;\r\n            height: 4" +
"00px;\r\n        }\r\n        \r\n    </style>\r\n");

});

WriteLiteral("\r\n<h1");

WriteLiteral(" class=\"math\"");

WriteLiteral(">Step 2 <small>");

            
            #line 17 "..\..\Views\Home\Step2.cshtml"
                          Write(Energy.envArr[Model.Env]);

            
            #line default
            #line hidden
WriteLiteral("</small></h1>\r\n<hr />\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Home\Step2.cshtml"
 using (Html.BeginForm("Step3", "Home", FormMethod.Post, new { name = "formInput", onsubmit = "return validate(this)" }))
{
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Home\Step2.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Home\Step2.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal math col-md-6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" id=\"hint\"");

WriteLiteral(" style=\"font-size: 16px; padding: 8px; border-radius: 4px;\"");

WriteLiteral(" class=\"col-lg-9 col-md-11 col-sm-8 col-xs-9 col-lg-offset-1 col-md-offset-0_5 co" +
"l-sm-offset-1 col-xs-offset-1\"");

WriteLiteral(">\r\n                At least 2 values are required.<br />\r\n                Only pa" +
"ired transition energies are available in this version.\r\n            </p>\r\n     " +
"   </div>\r\n        <br />\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"slEnv\"");

WriteLiteral(" class=\"control-label col-md-4 col-sm-3 col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(">SWNT Type</label>\r\n            <div");

WriteLiteral(" class=\"col-md-6 col-sm-4 col-xs-8 col-xs-offset-0_5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Views\Home\Step2.cshtml"
           Write(Html.DropDownListFor(model => model.Env, ViewBag.slEnv as List<SelectListItem>, new { id = "slEnv", @class = "form-control selectpicker", disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"slP1\"");

WriteLiteral(" class=\"control-label col-md-4 col-sm-3 col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(">Transition Energy 1</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-2 col-md-2_5 col-sm-2 col-xs-3 col-xs-offset-0_5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Views\Home\Step2.cshtml"
           Write(Html.DropDownListFor(model => model.P1, ViewBag.slType as List<SelectListItem>, new { id = "slP1", @class = "form-control selectpicker slp", title = @"\(E_{ii}\)"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <label");

WriteLiteral(" for=\"slP1\"");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">=</label>\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 col-xs-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Home\Step2.cshtml"
           Write(Html.EditorFor(model => model.Val1, new { htmlAttributes = new { id = "edVal1", @class = "form-control", pattern = @"[\d]+\.?[\d]*" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <label");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">\\(\\mathrm{eV}\\)</label>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"slP2\"");

WriteLiteral(" class=\"control-label col-md-4 col-sm-3 col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(">Transition Energy 2</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-2 col-md-2_5 col-sm-2 col-xs-3 col-xs-offset-0_5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 51 "..\..\Views\Home\Step2.cshtml"
           Write(Html.DropDownListFor(model => model.P2, ViewBag.slType as List<SelectListItem>, new { id = "slP2", @class = "form-control selectpicker slp", title = @"\(E_{ii}\)", disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <label");

WriteLiteral(" for=\"slP1\"");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">=</label>\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 col-xs-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\Home\Step2.cshtml"
           Write(Html.EditorFor(model => model.Val2, new { htmlAttributes = new { id = "edVal2", @class = "form-control", pattern = @"[\d]+\.?[\d]*" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <label");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">\\(\\mathrm{eV}\\)</label>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"slRBM\"");

WriteLiteral(" class=\"control-label col-md-4 col-sm-3 col-xs-12 col-xs-offset-0_5\"");

WriteLiteral(">RBM</label>\r\n            <div");

WriteLiteral(" class=\"col-lg-2 col-md-2_5 col-sm-2 col-xs-3 col-xs-offset-0_5\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral(" style=\"text-align: left\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(">\\(\\omega_{\\mathrm{RBM}}\\)</button>\r\n            </div>\r\n            <label");

WriteLiteral(" for=\"slP1\"");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">=</label>\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 col-xs-5\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 66 "..\..\Views\Home\Step2.cshtml"
           Write(Html.EditorFor(model => model.RBM, new { htmlAttributes = new { id = "edRBM", @class = "form-control", pattern = @"[\d]+\.?[\d]*" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <label");

WriteLiteral(" class=\"control-label col-auto\"");

WriteLiteral(">\\(\\mathrm{cm}^{-1}\\)</label>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-4 col-sm-offset-3 col-md-10 col-xs-offset-0_5\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 76 "..\..\Views\Home\Step2.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-6 col-xs-12 col-sm-12\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-striped math\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\Home\Step2.cshtml"
            
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Home\Step2.cshtml"
               
                var (li1, li2, li3) = Model.GetParams();
            
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 82 "..\..\Views\Home\Step2.cshtml"
            
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\Home\Step2.cshtml"
             for (int i = 0; i < li1.Count; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 85 "..\..\Views\Home\Step2.cshtml"
                
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\Home\Step2.cshtml"
                 for (int j = 0; j < li1[i].Length; j++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteAttribute("colspan", Tuple.Create(" colspan=", 4520), Tuple.Create("", 4539)
            
            #line 87 "..\..\Views\Home\Step2.cshtml"
, Tuple.Create(Tuple.Create("", 4529), Tuple.Create<System.Object, System.Int32>(li2[i][j]
            
            #line default
            #line hidden
, 4529), false)
);

WriteLiteral(">");

            
            #line 87 "..\..\Views\Home\Step2.cshtml"
                                      Write(Html.Raw(li1[i][j]));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 88 "..\..\Views\Home\Step2.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 90 "..\..\Views\Home\Step2.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <tr");

WriteLiteral(" style=\"text-align: left;\"");

WriteLiteral("><td");

WriteAttribute("colspan", Tuple.Create(" colspan=", 4669), Tuple.Create("", 4691)
            
            #line 91 "..\..\Views\Home\Step2.cshtml"
, Tuple.Create(Tuple.Create("", 4678), Tuple.Create<System.Object, System.Int32>(li2[0].Sum()
            
            #line default
            #line hidden
, 4678), false)
);

WriteLiteral(">");

            
            #line 91 "..\..\Views\Home\Step2.cshtml"
                                                               Write(Html.Raw(li3));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n        </table>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n<script>\r\n    $(page2Load(");

            
            #line 98 "..\..\Views\Home\Step2.cshtml"
            Write(Html.Raw(Model.Env));

            
            #line default
            #line hidden
WriteLiteral("));\r\n</script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
